apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        name: web
    spec:
      containers:
      - name: web
        image: zemond/web
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
